name: ci
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
# Prevent writing to the repository using the CI token.
# Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions: read-all
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: Install
        run: npm ci
      - name: Run tests and create report
        run: npm test
      - name: Update license headers
        run: npm run license-header
      - name: Format
        run: npm run format
      - name: Check Diff
        run: |
          [[ -z $(git status --porcelain | tee /dev/stderr) ]] || exit 1
