name: ci
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
# Prevent writing to the repository using the CI token.
# Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions: read-all
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-protobuf-conformance-ci-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-protobuf-conformance-ci-
      - name: make
        run: make all checkdiff
